# Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 8, 9])

print("arr = ", arr) 

print("Dimensió del array es ", arr.ndim) 

arr =  [1 2 3 4 5 6 8 9]
Dimensió del array es  1


In [2]:
def estadistic (arr):
    if arr.ndim > 1:
        print("Error!!!")
    else:
        min_ = np.amin(arr)
        max_ = np.amax(arr)
        range_ = np.ptp(arr)
        variance = np.var(arr)
        sd = np.std(arr)
        mean = np.mean(arr)
        median = np.median(arr)

        print ("Resum estadístic")
        print ("Minimum =", min_)
        print("Maximum =",max_)
        print("Range =",range_)
        print("Variance =",variance)
        print("Standard Deviation =", sd)
        print("Mean =", mean)
        print("Median =", median)    

In [3]:
estadistic (arr)

Resum estadístic
Minimum = 1
Maximum = 9
Range = 8
Variance = 6.9375
Standard Deviation = 2.6339134382131846
Mean = 4.75
Median = 4.5


# Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:

import random

import numpy as np

def random_matrix (R, cols):

        matrix = []

        rows =  0
         
          

        while  rows < cols:

            N = random.sample(R ,cols)

            matrix.append(N)

            rows = rows + 1
            

        return np.array(matrix)

print(random_matrix (range(100),5))

[[44 21  1 64 81]
 [43 56 90 65 48]
 [41 13 27 75 48]
 [99 34 24 58 23]
 [48  3 49 20 87]]


In [5]:
random_matrix(range(100),10)

array([[79,  6, 98, 47, 36, 52, 66, 54, 73, 39],
       [12, 64, 29, 30, 96, 91, 98, 60, 18, 82],
       [97, 76, 96, 43, 99,  6, 11, 69, 93, 27],
       [97, 62, 69, 85, 89,  0, 31, 28, 98, 70],
       [45, 34, 85, 54, 81, 87, 25, 18, 55,  1],
       [21, 49, 30, 40, 35, 18, 95, 16, 28, 75],
       [61, 77, 66, 41, 80, 47, 55, 32,  6, 88],
       [47, 24, 62, 66, 54, 23, 99, 95, 79, 82],
       [55, 77, 19, 67, 97, 82, 58, 26, 33,  1],
       [49, 96, 41, 53, 13, 44, 95, 30, 68, 70]])

## Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [6]:
import numpy as np

arr = ([10,23,35],[74,35,96],[75,58,39])


def suma_arr(arr):
    print(arr)
    sum_filas = np.sum(arr, axis = 0)
    print("\nSuma de las filas: \n", sum_filas)

    sum_columnas = np.sum(arr, axis = 1)
    print("\nSuma de las  columnas: \n", sum_columnas)

In [7]:
suma_arr(arr)

([10, 23, 35], [74, 35, 96], [75, 58, 39])

Suma de las filas: 
 [159 116 170]

Suma de las  columnas: 
 [ 68 205 172]


## Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.


## Pearson's correlation coefficient = covariance(X, Y) / (stdv(X) * stdv(Y))

In [15]:

import math
def correlationCoefficient(X, Y, n) :
    sum_X = 0
    sum_Y = 0
    sum_XY = 0
    squareSum_X = 0
    squareSum_Y = 0
    n = len(X)

    i = 0
    while i < n :
        # suma de los elementos del array X.
        sum_X = sum_X + X[i]
        
        # suma de los elementos del array Y.
        sum_Y = sum_Y + Y[i]
        
        # suma de X[i] * Y[i].
        sum_XY = sum_XY + X[i] * Y[i]
        

        # suma del cuadrado de los elementos del array.
        squareSum_X = squareSum_X + X[i] * X[i]
        squareSum_Y = squareSum_Y + Y[i] * Y[i]

        i = i + 1
        
    # usamos la formula para calcular el coeficiente de correlación.
    corr = (float)(n * sum_XY - sum_X * sum_Y)/(float)(math.sqrt((n * squareSum_X -sum_X * sum_X)* (n * squareSum_Y -sum_Y * sum_Y)))
    return corr



In [16]:
X = [15, 18, 21, 24, 27]
Y = [25, 25, 27, 31, 32]
n = len(X)

In [17]:
correlationCoefficient(X,Y,n)

0.9534625892455922

In [18]:
#Comprobamos que es correcto:
np.corrcoef(X, Y)



array([[1.        , 0.95346259],
       [0.95346259, 1.        ]])

#### El coeficiente de correlación de Pearson mide la asociación lineal entre variables. Su valor se puede interpretar así:

   


El valor del índice de correlación varía en el intervalo [ − 1 , 1 ] , indicando el signo el sentido de la relación:

### Si r = 1 
    existe una correlación positiva perfecta. El índice indica una dependencia total entre las dos variables denominada relación directa: cuando una de ellas aumenta, la otra también lo hace en proporción constante.
### Si 0 < r < 1  
    entonces existe una correlación positiva.
### Si r = 0 
    entonces no existe relación lineal pero esto no necesariamente implica que las variables son independientes: pueden existir todavía relaciones no lineales entre las dos variables.
### Si − 1 < r < 0 
    existe una correlación negativa.
### Si r = − 1  
    existe una correlación negativa perfecta. El índice indica una dependencia total entre las dos variables    llamada relación opuesta: cuando una de ellas aumenta, la otra cambia su signo en proporción constante.